### ISSUE TITLE
Discord /roll help alias and /roll help system error

### ISSUE THREAD

**Issue by ForestofAeshe** [Humblemonk/DiceMaiden#242] opened 2024-12-19 23:42 UTC
Attempting to use the slash command discord integration for dice maiden pulling up /roll help alias and /roll help system immediately populate the discord message:___" at the end and fail to perform.

/roll help works but is not listed as an option and only prior knowledge of other bots having a help variant allowed me to find the help menu and github. took 3-5 tries of variant syntax exploration.

Would appreciate these being A) listed in slash commandsand B) work in the slash command menu. Both in order to aid in learning how to use the bot as each dice bot has variants of similar syntax and commands but are different enough to need some review for experienced users or a visible help option for newcomers.

**Comment by Humblemonk** [comment] 2024-12-20 20:48
How frequent does the request timeout? Does it happen 24/7 for you? I just attempted to reproduce this on a few servers and was unable to. I also wasn't able to find anything in the bot logs that might point to whats occurring :/

**Comment by Humblemonk** [comment] 2024-12-29 01:35
Going to close this out as cannot reproduce. If this does crop up, I believe the issue is tied to a discord API issue that's outside my control. Similar scenario can happen with normal dice rolls

**Closed by Humblemonk** 2024-12-29 01:35 UTC

**Comment by ForestofAeshe** [comment] 2024-12-29 04:12
thank you. sorry. holidays got away from me and I did not have a chance to get you the data you requested.
